// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrknbfrwuolpfzbrqfco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlya25iZnJ3dW9scGZ6YnJxZmNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNjIzOTgsImV4cCI6MjA3MTkzODM5OH0.QTugKQYdefThSTjBOSC6yP2rfozBTGu-pcz3K04vcBc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});